language: android
sudo: false
jdk: oraclejdk8

android:
  components:
  # We need to install tools first, and twice, because it needs to be updated
  # so android-27 can be found.
  # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
  - tools
  - tools
  # Actual dependencies:
  - android-27
  - build-tools-26.0.2
  - extra-android-m2repository
  - extra-android-support
  - platform-tools

install:
# Install latest gradle android scala plugin, which supports recent android
# gradle plugins.
- git clone --depth=1 https://github.com/saturday06/gradle-android-scala-plugin ../gradle-android-scala-plugin
- sed -i -e 's/"com.android.tools.build:gradle:2.0.0"/"com.android.tools.build:gradle:2.0.0"/' ../gradle-android-scala-plugin/build.gradle
- sed -i -e 's/"org.scala-lang:scala-compiler:2.11.7"/"org.scala-lang:scala-compiler:2.11.12"/' ../gradle-android-scala-plugin/build.gradle
- sed -i -e 's/scalaCompileOptions.useAnt = false/\/\/ scalaCompileOptions.useAnt = false/' ../gradle-android-scala-plugin/src/main/groovy/jp/leafytree/gradle/AndroidScalaPlugin.groovy
- (cd ../gradle-android-scala-plugin && ./gradlew install)

script:
# Build APK.
- ./gradlew packageDebug
