language: android
sudo: false
jdk: oraclejdk8

android:
  components:
  # We need to install tools first, and twice, because it needs to be updated
  # so android-27 can be found.
  # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
  - tools
  - tools
  # Actual dependencies:
  - android-27
  - build-tools-26.0.2
  - extra-android-m2repository
  - extra-android-support
  - platform-tools

before_install:
- yes | sdkmanager "platforms;android-27"
